#!/usr/bin/env python3
# Copyright (c) 2026 — free to use and modify.
# SPDX-License-Identifier: BSD-3-Clause
"""
list_task_catalog.py
====================

Builds a catalog of EVERY Gymnasium task registered by Isaac Lab (and, optionally,
by your own external project) and tells you:

  * whether the task is Reinforcement Learning or something else (imitation learning),
  * which Isaac Lab workflow it uses (manager-based / direct / direct multi-agent),
  * which RL libraries it ships a config for (rl_games, rsl_rl, skrl, sb3),
  * whether YOUR external project can run it,
  * and the exact command line to launch it.

WHY THIS EXISTS
---------------
An external project generated by the Isaac Lab template wizard only contains a
`scripts/<rl_library>/train.py` for the libraries you picked in the wizard.
A task is runnable from your project only if the task registered a matching
`<library>_cfg_entry_point` in its `gym.register(...)` call. This script reads
those registrations and does the matching for you.

WHAT THIS SCRIPT DOES NOT DO
----------------------------
It does not train, does not launch Isaac Sim, does not touch your logs, and does not modify a
single file in your project or in the Isaac Lab install. It only reads and prints. Running it is
always safe.

HOW IT WORKS
------------
It parses the Python source files with the standard-library `ast` module and extracts every
`gym.register(...)` call. `ast` reads code as text and never executes it, so nothing in Isaac Lab
is imported or run. No GPU, no simulator. It finishes in about one second.

USAGE
-----
    Works in ANY external project made by the Isaac Lab template wizard, whatever it is called.
    No project name, task name or folder name is hard-coded anywhere in this file.

    # from the root of your external project
    python scripts/list_task_catalog.py

    # write the Markdown table to a file
    python scripts/list_task_catalog.py --markdown docs/TASK_CATALOG.md --csv docs/task_catalog.csv

    # only show what you can actually run today
    python scripts/list_task_catalog.py --only-runnable

    # only show locomotion tasks
    python scripts/list_task_catalog.py --filter velocity

    # point it at Isaac Lab manually if auto-detection fails
    python scripts/list_task_catalog.py --isaaclab-root C:\\Users\\me\\IsaacLab
"""

from __future__ import annotations

import argparse
import ast
import contextlib
import csv
import importlib.util
import os
import sys
from dataclasses import dataclass, field

# --------------------------------------------------------------------------------------
# 1. THE MAPPING TABLE  --  this is the heart of the whole script
# --------------------------------------------------------------------------------------
# Each Isaac Lab training script has a hard-coded default "agent config entry point".
# You can read these defaults yourself in:
#     IsaacLab/scripts/reinforcement_learning/<library>/train.py   (look for "--agent")
# The wizard copies those exact files into YOUR project as scripts/<library>/train.py,
# so the same defaults apply there.
#
#   script folder        default kwarg it looks for in gym.register()
#   -------------------  -------------------------------------------
#   scripts/rl_games/    rl_games_cfg_entry_point
#   scripts/rsl_rl/      rsl_rl_cfg_entry_point
#   scripts/skrl/        skrl_cfg_entry_point   (or skrl_<algorithm>_cfg_entry_point)
#   scripts/sb3/         sb3_cfg_entry_point
SCRIPT_VERSION = "1.2"

RL_LIBRARIES: dict[str, dict] = {
    "rl_games": {"entry_point": "rl_games_cfg_entry_point"},
    "rsl_rl": {"entry_point": "rsl_rl_cfg_entry_point"},
    "skrl": {"entry_point": "skrl_cfg_entry_point"},
    "sb3": {"entry_point": "sb3_cfg_entry_point"},
}

# Order used when the script recommends ONE command for a task that supports several
# libraries. rsl_rl first because it is the fastest to get running and prints the
# clearest learning metrics in the terminal.
PREFERRED_LIBRARY_ORDER = ["rsl_rl", "rl_games", "skrl", "sb3"]

# Extra, non-default entry points. They exist, but you must pass them explicitly with
# `--agent <name>` (rsl_rl) or `--algorithm <name>` (skrl).
EXTRA_ENTRY_POINTS = {
    "rsl_rl_with_symmetry_cfg_entry_point": ("rsl_rl", "--agent rsl_rl_with_symmetry_cfg_entry_point"),
    "rsl_rl_recurrent_cfg_entry_point": ("rsl_rl", "--agent rsl_rl_recurrent_cfg_entry_point"),
    "rsl_rl_distillation_cfg_entry_point": ("rsl_rl", "--agent rsl_rl_distillation_cfg_entry_point"),
    "rsl_rl_distillation_recurrent_cfg_entry_point": ("rsl_rl", "--agent rsl_rl_distillation_recurrent_cfg_entry_point"),
    "skrl_ippo_cfg_entry_point": ("skrl", "--algorithm IPPO"),
    "skrl_mappo_cfg_entry_point": ("skrl", "--algorithm MAPPO"),
    "skrl_amp_cfg_entry_point": ("skrl", "--algorithm AMP"),
}

# Entry points that are NOT reinforcement learning. A task that only has these cannot be
# launched by any of the four train.py scripts.
NON_RL_ENTRY_POINTS = {
    "robomimic_bc_cfg_entry_point": "imitation learning (robomimic behaviour cloning)",
}


# --------------------------------------------------------------------------------------
# 2. DATA MODEL
# --------------------------------------------------------------------------------------
@dataclass
class TaskRecord:
    """One `gym.register(...)` call, flattened into something we can put in a table."""

    task_id: str                      # e.g. "Isaac-Humanoid-v0"
    source: str                       # "Isaac Lab" or "Your project"
    workflow: str                     # "manager-based" | "direct" | "direct (multi-agent)"
    entry_point: str                  # the raw gym entry_point string
    cfg_entry_points: list[str] = field(default_factory=list)   # every *_cfg_entry_point key
    file: str = ""                    # where it was found, for debugging

    # ---- derived properties -------------------------------------------------------
    @property
    def supported_libraries(self) -> list[str]:
        """RL libraries this task ships a ready-made config for (default entry points)."""
        return [
            lib for lib, meta in RL_LIBRARIES.items()
            if meta["entry_point"] in self.cfg_entry_points
        ]

    @property
    def libraries_via_extra_entry_point(self) -> list[str]:
        """Libraries reachable only through a non-default entry point (AMP, IPPO, symmetry...)."""
        return sorted({
            lib for ep, (lib, _flag) in EXTRA_ENTRY_POINTS.items()
            if ep in self.cfg_entry_points and lib not in self.supported_libraries
        })

    @property
    def extra_options(self) -> list[str]:
        """Non-default entry points, e.g. IPPO/MAPPO for multi-agent, or symmetry variants."""
        return [
            f"{flag}" for ep, (_lib, flag) in EXTRA_ENTRY_POINTS.items()
            if ep in self.cfg_entry_points
        ]

    @property
    def learning_type(self) -> str:
        if self.supported_libraries or self.extra_options:
            return "RL"
        for ep, description in NON_RL_ENTRY_POINTS.items():
            if ep in self.cfg_entry_points:
                return description
        return "no agent config"

    @property
    def is_multi_agent(self) -> bool:
        return "multi-agent" in self.workflow


# --------------------------------------------------------------------------------------
# 3. THE PARSER  --  read gym.register(...) without executing anything
# --------------------------------------------------------------------------------------
def _is_gym_register(node: ast.AST) -> bool:
    """True for `gym.register(...)` / `gymnasium.register(...)` call nodes."""
    return (
        isinstance(node, ast.Call)
        and isinstance(node.func, ast.Attribute)
        and node.func.attr == "register"
        and isinstance(node.func.value, ast.Name)
        and node.func.value.id in ("gym", "gymnasium")
    )


def _literal(node: ast.AST) -> str | None:
    """Return the text of a string node. Handles both "plain" and f"{...}" strings."""
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    if isinstance(node, ast.JoinedStr):
        # f-string: rebuild it as readable text, e.g. "{__name__}.ant_env:AntEnv"
        parts = []
        for value in node.values:
            if isinstance(value, ast.Constant):
                parts.append(str(value.value))
            elif isinstance(value, ast.FormattedValue):
                parts.append("{" + ast.unparse(value.value) + "}")
        return "".join(parts)
    return None


def _detect_workflow(entry_point: str, source_file: str) -> str:
    """
    Manager-based tasks always register entry_point="isaaclab.envs:ManagerBasedRLEnv".
    Direct tasks point at their own env class, e.g. f"{__name__}.ant_env:AntEnv".
    To tell a direct single-agent task from a direct MULTI-agent one, we open the env
    module next door and look at what the class inherits from.
    """
    if "ManagerBasedRLEnv" in entry_point:
        return "manager-based"
    if "DirectMARLEnv" in entry_point:
        return "direct (multi-agent)"

    # Direct workflow: try to resolve "{__name__}.<module>:<Class>" to a sibling file.
    if entry_point.startswith("{") and ":" in entry_point:
        module_part, _, class_name = entry_point.partition(":")
        module_name = module_part.split(".")[-1]
        candidate = os.path.join(os.path.dirname(source_file), module_name + ".py")
        if os.path.isfile(candidate):
            try:
                with open(candidate, encoding="utf-8", errors="ignore") as fh:
                    text = fh.read()
                if f"class {class_name}(DirectMARLEnv)" in text:
                    return "direct (multi-agent)"
            except OSError:
                pass
    return "direct"


def scan_directory(root: str, source_label: str) -> list[TaskRecord]:
    """Walk a folder tree and return one TaskRecord per gym.register(...) found."""
    records: list[TaskRecord] = []
    if not root or not os.path.isdir(root):
        return records

    for dirpath, dirnames, filenames in os.walk(root):
        # skip noise: tests, caches, docs, build artefacts
        dirnames[:] = [
            d for d in dirnames
            if d not in {"test", "tests", "__pycache__", ".git", "docs", "build", "logs"}
        ]
        for filename in filenames:
            if not filename.endswith(".py"):
                continue
            path = os.path.join(dirpath, filename)
            try:
                with open(path, encoding="utf-8", errors="ignore") as fh:
                    tree = ast.parse(fh.read(), filename=path)
            except (SyntaxError, OSError):
                continue

            for node in ast.walk(tree):
                if not _is_gym_register(node):
                    continue

                task_id, entry_point, cfg_keys = None, "", []

                # positional form: gym.register("Id", "entry:Point")
                if node.args:
                    task_id = _literal(node.args[0]) or task_id
                    if len(node.args) > 1:
                        entry_point = _literal(node.args[1]) or ""

                # keyword form (this is what Isaac Lab actually uses)
                for kw in node.keywords:
                    if kw.arg == "id":
                        task_id = _literal(kw.value) or task_id
                    elif kw.arg == "entry_point":
                        entry_point = _literal(kw.value) or entry_point
                    elif kw.arg == "kwargs" and isinstance(kw.value, ast.Dict):
                        for key in kw.value.keys:
                            key_text = _literal(key)
                            if key_text and key_text.endswith("_cfg_entry_point"):
                                cfg_keys.append(key_text)

                if not task_id:
                    continue  # id built dynamically — nothing useful to report

                records.append(
                    TaskRecord(
                        task_id=task_id,
                        source=source_label,
                        workflow=_detect_workflow(entry_point, path),
                        entry_point=entry_point,
                        cfg_entry_points=cfg_keys,
                        file=os.path.relpath(path, root),
                    )
                )
    return records


# --------------------------------------------------------------------------------------
# 4. LOCATING ISAAC LAB AND YOUR PROJECT
# --------------------------------------------------------------------------------------
def find_isaaclab_tasks_dir(explicit_root: str | None) -> tuple[str | None, str]:
    """
    Return (folder_to_scan, how_we_found_it).

    Works for BOTH install styles:
      * cloned repo + `pip install -e`  ->  <repo>/source/isaaclab_tasks
      * plain pip install              ->  <site-packages>/isaaclab_tasks
    """
    if explicit_root:
        candidate = os.path.join(explicit_root, "source", "isaaclab_tasks")
        if os.path.isdir(candidate):
            return candidate, "--isaaclab-root argument"
        if os.path.isdir(explicit_root):
            return explicit_root, "--isaaclab-root argument (scanned as-is)"

    # find_spec only LOCATES the package, it does not import it — so no Isaac Sim start-up.
    try:
        spec = importlib.util.find_spec("isaaclab_tasks")
        if spec and spec.origin:
            return os.path.dirname(spec.origin), "installed `isaaclab_tasks` package"
    except (ImportError, ValueError):
        pass

    env_root = os.environ.get("ISAACLAB_PATH")
    if env_root:
        candidate = os.path.join(env_root, "source", "isaaclab_tasks")
        if os.path.isdir(candidate):
            return candidate, "ISAACLAB_PATH environment variable"

    for guess in [
        os.path.join(os.path.expanduser("~"), "IsaacLab"),
        os.path.join(os.getcwd(), "..", "IsaacLab"),
        os.path.join(os.getcwd(), "IsaacLab"),
    ]:
        candidate = os.path.join(guess, "source", "isaaclab_tasks")
        if os.path.isdir(candidate):
            return candidate, f"found at {os.path.normpath(guess)}"

    return None, "NOT FOUND"


def _looks_like_project_root(path: str) -> bool:
    """True if <path>/scripts/ contains at least one of the four RL script folders."""
    scripts_dir = os.path.join(path, "scripts")
    return any(os.path.isdir(os.path.join(scripts_dir, lib)) for lib in RL_LIBRARIES)


def default_project_root() -> str:
    """
    Work out where the external project is, without depending on the folder you launched from.

    Strategy: start at this script's own location, walk upwards, and return the first folder
    that has a scripts/ directory containing rl_games/, rsl_rl/, skrl/ or sb3/. Then do the same
    from the current working directory. This makes all of these behave identically:

        <project>\\scripts>  python list_task_catalog.py
        <project>>          python scripts\\list_task_catalog.py
        C:\\Users\\you>       python <YourProject>\\scripts\\list_task_catalog.py
    """
    for origin in (os.path.dirname(os.path.abspath(__file__)), os.getcwd()):
        candidate = origin
        for _ in range(5):  # don't wander off to C:\
            if _looks_like_project_root(candidate):
                return candidate
            parent = os.path.dirname(candidate)
            if parent == candidate:
                break
            candidate = parent
    # nothing convincing found -- fall back to the parent of a folder literally called "scripts"
    here = os.path.dirname(os.path.abspath(__file__))
    if os.path.basename(here).lower() == "scripts":
        return os.path.dirname(here)
    return os.getcwd()


def detect_available_libraries(project_root: str) -> dict[str, bool]:
    """Look inside <project_root>/scripts/ for the RL script folders the wizard created."""
    scripts_dir = os.path.join(project_root, "scripts")
    return {lib: os.path.isdir(os.path.join(scripts_dir, lib)) for lib in RL_LIBRARIES}


# --------------------------------------------------------------------------------------
# 5. DECIDING "CAN MY PROJECT RUN THIS?" AND BUILDING THE COMMAND
# --------------------------------------------------------------------------------------
def evaluate(record: TaskRecord, lib_status: dict[str, bool]) -> tuple[str, str]:
    """Return (runnable_verdict, launch_command)."""
    # Best case: the task ships a config under a library's DEFAULT entry point, and you
    # have that library's script folder.
    for lib in PREFERRED_LIBRARY_ORDER:
        if lib in record.supported_libraries and lib_status.get(lib):
            command = f"python scripts/{lib}/train.py --task={record.task_id}"
            if record.is_multi_agent and lib == "skrl":
                command += " --algorithm IPPO"
            return "YES", command

    # Also YES: the task files its config under a non-default entry point (AMP, IPPO/MAPPO,
    # symmetry, distillation...). Same script folder, you just have to name the algorithm on
    # the command line -- so the flag goes straight into the command and you never think
    # about it again.
    for entry_point, (lib, flag) in EXTRA_ENTRY_POINTS.items():
        if entry_point in record.cfg_entry_points and lib_status.get(lib):
            return "YES", f"python scripts/{lib}/train.py --task={record.task_id} {flag}"

    # The task DOES have a config for a library the template wizard knows how to generate --
    # you just did not tick that library when you ran the wizard. Fixable: copy the folder in.
    needed = record.supported_libraries or record.libraries_via_extra_entry_point
    if needed:
        return f"NO \u2014 but supported by Project Wizard ({', '.join(needed)})", "-"

    # Nothing any train.py can reach: imitation learning, or no agent config at all.
    # Either way there is nothing you can do about it, so the verdict is just "NO".
    return "NO", "-"


# --------------------------------------------------------------------------------------
# 6. OUTPUT
# --------------------------------------------------------------------------------------
def build_rows(records: list[TaskRecord], lib_status: dict) -> list[dict]:
    """Three columns and nothing else: the task name, the verdict, the command."""
    rows = []
    # this project's own tasks first, then Isaac Lab's, each alphabetically
    for rec in sorted(records, key=lambda r: (r.source == "Isaac Lab", r.task_id)):
        verdict, command = evaluate(rec, lib_status)
        rows.append({
            "Task": rec.task_id,
            "Runnable in your project?": verdict,
            "Launch command": command,
        })
    return rows


def to_markdown(rows: list[dict], lib_status: dict, sources: dict) -> str:
    lines = ["# Isaac Lab Task Catalog", "",
             "| Task | Runnable in your project? | Launch command |",
             "|---|---|---|"]
    for row in rows:
        command = row["Launch command"]
        command = "-" if command == "-" else f"`{command}`"
        lines.append(f"| {row['Task']} | {row['Runnable in your project?']} | {command} |")
    lines.append("")
    return "\n".join(lines)


def print_console(rows: list[dict], lib_status: dict, sources: dict) -> None:
    """Print the table, sized to whatever the longest task name happens to be."""
    name_width = max(len(r["Task"]) for r in rows)
    verdict_width = max(len(r["Runnable in your project?"]) for r in rows)

    header = f"{'TASK':<{name_width}}  {'RUNNABLE IN YOUR PROJECT?':<{verdict_width}}  LAUNCH COMMAND"
    print()
    print(header)
    print("-" * len(header))
    for row in rows:
        print(
            f"{row['Task']:<{name_width}}  "
            f"{row['Runnable in your project?']:<{verdict_width}}  "
            f"{row['Launch command']}"
        )
    print("-" * len(header))

    found = [lib for lib, has_script in lib_status.items() if has_script]
    yes = sum(1 for r in rows if r["Runnable in your project?"] == "YES")
    project_path = sources.get("project", "")
    project_name = os.path.basename(project_path.rstrip(os.sep)) or project_path
    print(f"{yes} of {len(rows)} runnable   |   script folders found: {', '.join(found) or 'none'}"
          f"   |   project: {project_name}")
    print(f"(list_task_catalog.py v{SCRIPT_VERSION})")
    print()


# --------------------------------------------------------------------------------------
# 7. MAIN
# --------------------------------------------------------------------------------------
def main() -> int:
    parser = argparse.ArgumentParser(
        description="Catalog every Isaac Lab task and show which ones your external project can run.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--isaaclab-root", default=None,
                        help="Path to your IsaacLab clone. Auto-detected if omitted.")
    parser.add_argument("--project-root", default=None,
                        help="Root of your external project (the folder containing 'scripts'). "
                             "By default this is worked out from where this script file lives.")
    parser.add_argument("--markdown", nargs="?", const="TASK_CATALOG.md", default=None,
                        help="Write a Markdown table. Default filename: TASK_CATALOG.md")
    parser.add_argument("--csv", nargs="?", const="task_catalog.csv", default=None,
                        help="Write a CSV file. Default filename: task_catalog.csv")
    parser.add_argument("--only-runnable", action="store_true",
                        help="Only list tasks your project can run today.")
    parser.add_argument("--only-rl", action="store_true",
                        help="Hide tasks no train.py can ever reach (imitation learning / no agent config).")
    parser.add_argument("--filter", default=None,
                        help="Case-insensitive substring filter on the task name, e.g. --filter velocity")
    parser.add_argument("--quiet", action="store_true", help="Do not print the table to the terminal.")
    args = parser.parse_args()

    # Windows consoles default to cp1252 and choke on the em dash in the verdicts.
    with contextlib.suppress(AttributeError, OSError):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")

    project_root = os.path.abspath(args.project_root or default_project_root())
    isaaclab_tasks_dir, how = find_isaaclab_tasks_dir(args.isaaclab_root)

    if not isaaclab_tasks_dir:
        print("ERROR: could not locate Isaac Lab's task package.", file=sys.stderr)
        print("Fix: activate your Isaac Lab conda environment, or pass --isaaclab-root "
              "C:\\path\\to\\IsaacLab", file=sys.stderr)
        return 1

    records = scan_directory(isaaclab_tasks_dir, "Isaac Lab")

    # Also scan this project's own tasks. Whatever the project is called, its tasks live under
    # <project>/source/, so we just walk that folder -- no project name is ever assumed.
    # Whatever the project is called, its tasks live under <project>/source/.
    project_source = os.path.join(project_root, "source")
    if os.path.isdir(project_source):
        records += scan_directory(project_source, os.path.basename(project_root.rstrip(os.sep)))

    # de-duplicate: the same task id can be registered in more than one place
    unique: dict[str, TaskRecord] = {}
    for rec in records:
        unique.setdefault(rec.task_id, rec)
    records = list(unique.values())

    lib_status = detect_available_libraries(project_root)
    if not any(lib_status.values()):
        print()
        print("!" * 78)
        print("WARNING: no RL script folders found, so every task will be reported as NO.")
        print(f"         Looked in: {os.path.join(project_root, 'scripts')}")
        print("         That folder should contain rl_games/, rsl_rl/, skrl/ or sb3/.")
        print("         If your project is elsewhere, pass it explicitly, for example:")
        print("             python scripts/list_task_catalog.py "
              "--project-root C:\\path\\to\\<YourProject>")
        print("!" * 78)

    rows = build_rows(records, lib_status)

    if args.filter:
        needle = args.filter.lower()
        rows = [r for r in rows if needle in r["Task"].lower()]
    if args.only_rl:
        rows = [r for r in rows if r["Runnable in your project?"] != "NO"]
    if args.only_runnable:
        rows = [r for r in rows if r["Runnable in your project?"] == "YES"]

    if not rows:
        print("[warn] No tasks matched. Try removing --filter / --only-runnable.")
        return 0

    sources = {"isaaclab": isaaclab_tasks_dir, "project": project_root}

    if not args.quiet:
        print_console(rows, lib_status, sources)

    if args.markdown:
        os.makedirs(os.path.dirname(os.path.abspath(args.markdown)), exist_ok=True)
        with open(args.markdown, "w", encoding="utf-8") as fh:
            fh.write(to_markdown(rows, lib_status, sources))
        print(f"[ok] Markdown table written to {os.path.abspath(args.markdown)}")

    if args.csv:
        os.makedirs(os.path.dirname(os.path.abspath(args.csv)), exist_ok=True)
        with open(args.csv, "w", newline="", encoding="utf-8") as fh:
            writer = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
            writer.writeheader()
            writer.writerows(rows)
        print(f"[ok] CSV written to {os.path.abspath(args.csv)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
